### ISSUE TITLE
Admin-Bereich Ordnerauswahl

### ISSUE THREAD

**Issue by srueegger** [srueegger/www#101]
Bugfix für die Ordnerauswahl im Adminbereich -> die **Scheisse** nervt mich! :D

**Comment by aesche** [comment]
Du hast das doch bestimmt schon den anderen Entwicklern des CMS reported, oder? Können die da nicht mal schauen?

**Comment by srueegger** [comment]
Ich hab denen schon einiges reported - bisher wurde dort aber wenig gemacht - weil die dortigen Prioritäten zurzeit beim Installer liegen
