### ISSUE TITLE
Alle Textseiten sind voll mit Doppelleerzeichen

### ISSUE THREAD

**Issue by aesche** [srueegger/www#108]
Kannst du @srueegger die gesamthaft suchen und beheben oder muss ich das manuell machen?

**Comment by srueegger** [comment]
öhm hast du ein Beispiel? Ich hab gerade Random eine aufgemmacht und nichts entsprechendes gesehen.

**Comment by srueegger** [comment]
Sollte jetzt überall behoben sein.
