### ISSUE TITLE
Meal-Anzeige: Hardcode "Die vollständige Adresse wird angemeldeten Gästen 24 Stunden vor Meal-Beginn per E-Mail mitgeteilt"

### ISSUE THREAD

**Issue by aesche** [srueegger/www#57]

**Comment by srueegger** [comment]
Wurde so gelöst, dass dieser Text bei Restaurant Events nicht angezeigt wird. https://github.com/srueegger/www/commit/8263956d035f498c73aefd3045b3ed11977a6e6b
