### ISSUE TITLE
Verlinkte Karte bei "PLZ Ort" in Meal-Ansicht

### ISSUE THREAD

**Issue by aesche** [srueegger/www#65]
https://www.google.ch/maps/place/PLZ

**Comment by srueegger** [comment]
Erledigt: https://github.com/srueegger/www/commit/ad5b43711a6f33352bd512f983292bf132e32301

**Comment by srueegger** [comment]
Karte als eigener Punkt "Karte: Icon" Anzeigen. Bei Restaurant und Special Meal Adresse direkt anzeigen.

**Comment by aesche** [comment]
Bei Spezial-Meals nur wenn (noch zu programmierende) Auswahl "Adresse offen anzeigen" gewählt wurde.
