### ISSUE TITLE
Kontrollieren, ob überprüfte Profildaten nicht mehr bearbeitet werden können nach Beantragung der Verifizierung

### ISSUE THREAD

**Issue by aesche** [srueegger/www#66]
Habe den Verdacht, dass die Sperre dann noch nicht besteht und erst bei Abschluss der Verifizierung einsetzt!?

**Comment by srueegger** [comment]
Eben mit Test-User getestet - Profil kann nicht mehr bearbeitet werden.

LG Sam

![bildschirmfoto 2015-05-08 um 11 50 52](https://cloud.githubusercontent.com/assets/11472914/7534201/83745360-f578-11e4-919d-00c18629b02b.png)
