### ISSUE TITLE
Offene Registrierungen anzeigen

### ISSUE THREAD

**Issue by srueegger** [srueegger/www#68]
Eine Seite einrichten, in der alle **offenen** Registrierungen angezeigt werden. In dieser Seite soll auch der Profil-Aktivierungslink angezeigt werden für persönliche E-Mails.

**Comment by srueegger** [comment]
Erledigt: https://github.com/srueegger/www/commit/75180b167261dfdec1fc2ecd867186736dd94de6

Die Offenen Registrierungen findet man im Administrationsbereich: Unter Benutzer->Verwalten

**Comment by aesche** [comment]
Auf der Seite sollte auch eine Liste aller Organisationsprofile ersichtlich sein

**Comment by aesche** [comment]
Kann bei beiden existierenden Tabellen eine editierbare Spalte "Kontaktiert" -> Ja/Nein (für erneute Zusendung des Reg-Links, bzw Versendung der Begrüssungs-PN) hinzugefügt werden?

Kann eine E-Mail-Benachrichtigung eingerichtet werden, falls ein Eintrag aus diesen Listen gelöscht wird?

**Comment by srueegger** [comment]
Eine zusätzliche E-Mail Benachrichtigung macht wenig Sinn. Wir bekommen doch bereits ein Mail wenn jemand seine RegLink anklickt.

**Comment by aesche** [comment]
Missverständnis. Wenns mal passiert, dass man versehentlich auf das Löschen-Kreuz kommt, auch bei existierenden Mitgliedern, insbesondere wenn noch sonstjemand Zugriff auf die Liste bekommt (Versendung der Begrüssungs-PN zb), wäre es gut wenn du davon erfahren würdest.

**Comment by srueegger** [comment]
Das darf einfach nicht passieren. Die Daten sind nach einer Löschung auch nicht widerherstellbar ob ich nun eine Benachrichtigung bekomme oder nicht.

Diese Liste wird nicht weitere geöffnet. Es gibt einen Grund das das ein Administrationsbereich ist, da wird nicht "Hinz & Kunz" Zugriff darauf haben. Finde es einfach eine Zeitverschwendung, in den Bereich zu viel Energie zu investieren.

Die Leute die hier Zugriff erhalten müssen wissen was sie tun. Das mit dem zusätzlichen Feld ist auch eine relativ komplexe Sache für so gut wie keinen Mehrwert. Die Begrüssungsmails / PN finde ich automatisiert immer noch besser ^^ - Falls doch manuell muss das in die Community ausgelagert werden, diese Personen die das machen werden, werden bestimmt keinen Zugriff auf den Adminbereich erhalten ^^

Org Profile kann ich noch reinnehmen.

**Comment by srueegger** [comment]
Auflistung der Organisationsprofile beendet: https://github.com/srueegger/www/commit/8578c22560eb0a49ef20ef89273a0c733075f947

Ich schliesse hier: würde es gut finden wenn alles zu diesem Thema hier diskutiert wird #91
