### ISSUE TITLE
Hochgeladene Meal-Bilder nicht vom Server löschen...

### ISSUE THREAD

**Issue by aesche** [srueegger/www#79]
...sonst gehen alte Meals bei Reaktivierung mit Bild-Wechsel kaputt.

**Comment by srueegger** [comment]
Die Mealbilder werden **nicht** aus der Datenbank sondern vom Server gelöscht

**Comment by srueegger** [comment]
Erledigt: https://github.com/srueegger/www/commit/3c0203be408f1a70e6624dce0524810b95f0100c
