### ISSUE TITLE
Automatischer Tweet von Events

### ISSUE THREAD

**Issue by srueegger** [srueegger/www#80]
Wenn der Tweet mehr als 140 Zeichen hat, akzeptiert Twitter den Tweet nicht. Zeichenlänge muss dringend vor dem Absenden kontrolliert werden. Wenn die Zeichenlänge zu lang ist, muss der Titel gekürzt werden.

Vorschlag Stefan:
Neues $Meal-Typ: $Meal-Name am $Meal-Datum, $Meal-Zeit #SocialMeal Anmeldung: $Meal-Link

**Comment by aesche** [comment]
Mein Vorschlag lässt mindestens (bei Restaurant-Meals) 50 Zeichen für den Titel frei.
-> Standardmässig nur 50 Zeichen aus Titel übernehmen?

**Comment by srueegger** [comment]
Erledigt wie im Vorschlag: https://github.com/srueegger/www/commit/d451aa2b39b35e78a9221797308c62b98cf70418

**Comment by aesche** [comment]
$Meal-Name fehlt noch, nach $Meal-Typ: Neues Spezial-Meal am 22.05.2015, 12:00 ‪#‎SocialMeal‬ Anmeldung: https://t.co/sDeu5girww

**Comment by aesche** [comment]
Doppelpunkt nach Mealtyp fehlt noch
