### ISSUE TITLE
Meals mit abgelaufenem Meal-Datum sollten nicht mehr bearbeitet werden können!

### ISSUE THREAD

**Issue by aesche** [srueegger/www#81]
(auch wenn sie keine Anmeldungen hatten). Sonst können abgelaufene Meals bearbeitet und neu gesetzt anstatt reaktiviert werden, dann bleibt ID und F&A erhalten, keine neue Twitter- und FB-Posts werden generiert.

**Comment by srueegger** [comment]
Erledigt: https://github.com/srueegger/www/commit/eec5d95ea55c1779024c74cf77a7ffc2720cc922
