### ISSUE TITLE
i-Buttons von 2. Registrierungsschritt in "Profil bearbeiten" einbauen

### ISSUE THREAD

**Issue by aesche** [srueegger/www#82]
i-Buttons hinter:
- Nachname
- Geburtsdatum
- Strasse und Hausnummer
- PLZ und Wohnort
- Tel-Nr.

**Comment by srueegger** [comment]
Ist doch bereits eingebaut.

![bildschirmfoto 2015-05-15 um 09 10 21](https://cloud.githubusercontent.com/assets/11472914/7648353/4c70cb4a-fae2-11e4-8810-c54af2c3191d.png)

**Comment by srueegger** [comment]
erledigt: https://github.com/srueegger/www/commit/72eaba62073cdb9713f4626fa7071f53603bcd09
