### ISSUE TITLE
Bei allen Homepage-Eingabe-Feldern: http-Überprüfung

### ISSUE THREAD

**Issue by aesche** [srueegger/www#86]
Wenn die ersten 4 Zeichen nicht http sind, füge automatisch http:// zum Linkanfang hinzu

**Comment by aesche** [comment]
Nach Einbau bitte alle bisherigen Homepage-Eingabefelder (Organisationsprofile, social media profile) überprüfen und allenfalls korrigieren (ausser beim Org-Profil Foodsharing, der weiss es schon).

**Comment by srueegger** [comment]
Erledigt https://github.com/srueegger/www/commit/ac1246c8e51e2bc2da34818e364a1c88d027f1fc

**Comment by srueegger** [comment]
Neuer Bug: Wenn der User keine Eingabe macht wird automatisch http:// eingesezt.

**Comment by srueegger** [comment]
Gelöst: https://github.com/srueegger/www/commit/1d26f840f8fbb56ac02035c20063cd37828636ba und https://github.com/srueegger/www/commit/da76052dbe8328cd4b9ca8cbe2aa3d6f84b60e8d
