### ISSUE TITLE
Suche muss mindestens 3 Zeichen lang sein

### ISSUE THREAD

**Issue by aesche** [srueegger/www#90]

**Comment by srueegger** [comment]
Erledigt: https://github.com/srueegger/www/commit/fb5efb41afd4abfc5f86d5528ca5bf4d94c3a4dc

**Comment by aesche** [comment]
Hast du gleichzeitig auch noch eingebaut, dass keine Sonderzeichen gesucht werden können?
Wär ok für Benutzerkonten wenn im Nick keine Sonderzeichen mehr zugelassen werden, aber schwierig für Textsuche

**Comment by srueegger** [comment]
Nein: schau - #74

**Comment by aesche** [comment]
Als du das geschrieben hast definitiv noch nicht, jetzt funktionierts aber :)
