### ISSUE TITLE
E-Mail mit allen Anmeldungen an Gastgeber bei Anmeldeschluss eines Spezial-Meals an zusätzliche Adresse verschicken...

### ISSUE THREAD

**Issue by aesche** [srueegger/www#94]
... entweder an im Organisations-Profil hinterlegte Adresse.
... oder bei Erstellung des Meals frei eingebbare E-Mail-Adresse bei Auswahl dieser freiwilligen Funktion.

... anstatt für das Sammel-Anmeldungs-Mail bei Anmeldeschluss könnte diese Funktion auch für die sofortigen Mails bei individuellen An- und Abmeldungen entwickelt werden.

**Comment by aesche** [comment]
Christoph vom kug-Mittagstisch wünscht die Funktion so, dass das zusammenfassende E-Mail bei Anmeldeschluss zusätzlich & automatisch an die Adresse im Organisationsprofil geschickt wird.

Sobald das umgesetzt wird, bietet er den kommenden Mittagstisch ohne Hinweis auf externe Anmeldung an.

Vorschlag: Checkbox (oder Drop-Down mit Auswahl "Nein" (Standard) und "Ja") bei Erstellung von Spezial-Meals, fakultativer Bereich:
- Text: Abschluss-Email an Organisationsadresse schicken
- i-Button: Durch Aktivierung dieser Auswahl wird das automatische E-Mail mit allen definitiven Anmeldungen bei Anmeldeschluss zusätzlich an die im Organisationsprofil hinterlegte E-Mail-Adresse verschickt.

Zu bedenkende Problematik: Funktion muss wohl allen angezeigt werden, auch wenn sie kein Organisationsprofil auswählen (können/wollen). Kann sofort überprüft werden, ob ein Organisationsprofil gewählt wurde, wenn Zusatzfunktion ausgewählt wurde? Alternativer Vorschlag: Keine Fehlermeldung, wenn keine Organisations-E-Mail-Adresse gefunden wird, wird einfach kein zusätzliches E-Mail verschickt.

**Comment by srueegger** [comment]
Alternativer Vorschlag:

Die Administratoren vom Organisationsprofil können  beim "Organisationsprofil bearbeiten" auswählen ob Das Abschlussmail auch an die e-Mail Adresse vom Organisationsprofil versendet werden können?

Geht es hier nur um das letzte Mail oder auch bei den jeweils einzelnen Anmeldungen?

Kannst du noch einen Mailtext schreiben, damit die Organisationen ihre Organisationsmail bestätigen/verifizieren können?

Also wir schicken den Organisationen auf Wunsch ein Mail an die OrgMail Adresse dort ist ein Link, wenn sie den anklicken ist die Mailadresse verifiziert und wir wissen dass sie stimmt.

Danach wird die Option im Organisationsprofil bearbeiten freigeschaltet, das Mails auch an Organisationsprofile versendet werden können.

Wäre so meine Idee dazu

**Comment by aesche** [comment]
Finde deine Lösung unterdessen beinahe besser, die Funktion fix im Organisationsprofil ist glaubs übersichtlicher (Opt-In)
Es geht nur um das letzte E-Mail an den Gastgeber bei Anmeldeschluss, aber bei Erfolg wie bei Misserfolg.

Organisationsprofil bearbeiten:
- E-Mail-Feld: Jederzeit bearbeitbar, wenn neue E-Mail gespeichert wird, geht aber Verifizierung verloren.
- Hinter E-Mail: Grünes Häckchen oder rotes Kreuz ob E-Mail verifiziert ist.
- Dahinter: Button "E-Mail-Verifizierung beantragen" (nur aktiv wenn e-Mail nicht verifiziert ist).
- Neue Zeile: Checkbox "E-Mail bei Anmeldeschluss auch an diese E-Mail-Adresse schicken"
- Dahinter: i-Button: "Wenn diese Option ausgewählt und die Organisations-E-Mail-Adresse verifiziert ist, wird bei mit diesem Organisationsprofil organisierten Spezial-Meals das automatische E-Mail bei Anmeldeschluss, welches über alle definitiven Anmeldungen informiert, auch an diese E-Mail-Adresse geschickt."

- E-Mail-Vorlage für E-Mail-Verifizierung:
Titel: Verifiziere deine Organisations-E-Mail-Adresse auf Social Meal
Text:
>>
Liebe*r Administrator*in von $Organisationsname

Soeben hast du auf Social Meal die Verifizierung dieser E-Mail-Adresse für das Organisationsprofil $Link[$Organisationsname] beantragt.

Klicke auf diesen Link um die E-Mail-Adresse zu verifizieren: $Link
Danach kannst du unter Link[Organisationsprofil bearbeiten] die Option, dass bei deinen Spezial-Meals das automatische E-Mail bei Anmeldeschluss, welches dich über alle definitiven Anmeldungen informiert, auch an diese E-Mail-Adresse versandt wird, aktivieren.

Vielen dank für dein Engagement auf Social Meal.
Social Meal

Signatur
<<

**Comment by srueegger** [comment]
Erledigt. Folgendermassen läuft das ab:

Dort wo man Organisationsprofile bearbeiten kann, kann man seine Organisationsmail Adresse verifizieren lassen. Danach erhält man ein Mail mit einem Link. Wenn man diesen Link anklickt ist die E-Mail Adresse verifiziert.

Ab diesem Moment kann man die Option setzen: für zusätzliche E-Mail Benachrichtigung für das "Nach Anmeldeschlussmail" auch an Organisationsmail Adresse senden.

Wenn beim zukünftigen Bearbeiten des Organisationsprofils die E-Mail Adresse geändert wird, wird der Verifizierungststatus wie die gesetzte Option wieder gelöscht. Eine E-Mail Adresse kann jederzeit wieder neu verifiziert werden.
