### ISSUE TITLE
Organisationsprofile: Anzeige von aktuellen Meals der Organisation

### ISSUE THREAD

**Issue by aesche** [srueegger/www#95]

**Comment by aesche** [comment]
hübsch gelöst *-*
Zur Perfektion könnte man den Text wohl beinahe noch stärker kürzen, und vielleicht wäre noch ein zusätzlicher Abstand oberhalb von "Aktuelle Meals" möglich? What about vergangene Meals (wenn, dann zb als Einzeiler, nur Titel ohne Bild, Hauptsache verlinkt)?

**Comment by srueegger** [comment]
Kann man machen ^^

**Comment by srueegger** [comment]
* Abstand wurde eingebaut
* Vergangene Meals werden angezeigt (sofern es welche hat) ^^
* Meal-Datum wird nun ebenfalls noch angezeigt.

Die Details sind hier: https://github.com/srueegger/www/commit/efc1c3257afd617d0fb5bf76a2657360d760267e
